export const StgRoutes = {
  OVERVIEW: 'overview',
  ALERT: 'alert',
  BAR: 'bar',
  BUTTON: 'button',
  CODE_BLOCK: 'code-block',
  FIGURE: 'figure',
  HIGHLIGHT: 'highlight',
  IMAGE: 'image',
  ICON: 'icon',
  INPUT: 'input',
  LINK: 'link',
  LIST: 'list',
  MODAL: 'modal',
  PARAGRAPH: 'paragraph',
  SPINNER: 'spinner',
  SUBTITLE: 'subtitle',
  TITLE: 'title',
  TABLE: 'table'
};
